### ISSUE TITLE
Register `LBSEC-` prefix in OSV schema

### ISSUE THREAD

**Issue by achrinza** [loopbackio/security#14]
This issue is to track registering of the `LBSEC-` prefix in https://github.com/ossf/osv-schema.

**Comment by oliverchang** [comment]
Hi there from an OSV maintainer! Very excited to see this! Please feel free to create a PR any time for this.

**Comment by achrinza** [comment]
Hi @oliverchang! I've went ahead and opened https://github.com/ossf/osv-schema/pull/43. Do reach out if additional info/work is needed from my end. :-)

**Comment by achrinza** [comment]
Closing as done.
